# Generated by Django 6.1.1 on 2026-09-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SERVER', 'Server'), ('KITCHEN', 'Kitchen'), ('DRIVER', 'Driver'), ('MANAGER', 'Manager')], max_length=20),
        ),
    ]
