# Generated by Django 6.1.1 on 2026-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('ORDERING', 'Ordering'), ('PREPARING', 'Preparing'), ('FOOD_SERVED', 'Food_served'), ('PAYMENT_PENDING', 'Payment_pending')], default='AVAILABLE', max_length=20),
        ),
    ]
