# Generated by Django 6.1.1 on 2026-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ORDERING', 'Ordering'), ('PREPARING', 'Preparing'), ('FOOD_SERVED', 'Food served'), ('PAYMENT_PENDING', 'Payment pending')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
