# Generated by Django 6.1.1 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
