# Generated by Django 6.1.1 on 2026-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menucategory_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'menu categories'},
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
